eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# python url
ai:
  service:
    url: https://algotalk.kr

spring:
  cloud:
    openfeign:
      client:
        config:
          aiService:
            url: ${ai.service.url}